include "common/check"

def test_print(I x) {
    pushi(x)
    printi check("printi")
    prints("\n")
    popi
}

def test_add(I x, I y) {
    pushi(x) printi prints(" + ")
    pushi(y) printi prints(" = ")
    addi check("addi")
    printi prints("\n")
    popi
}

def test_sub(I x, I y) {
    pushi(x) printi prints(" - ")
    pushi(y) printi prints(" = ")
    swapi
    subi check("subi")
    printi prints("\n")
    popi
}

def main() {
    // // printing
    test_print(0x80000000)
    test_print(0xFFFFFFFF)
    test_print(0x7FFFFFFF)

    // adding
    test_add(0x0000FFFF, 1)
    test_add(0x00FFFFFF, 0x00FFFFFF)

    // adding
    test_sub(10, 20)
    test_sub(0x1000, 1)
    test_sub(-42, -84)
    test_sub(0xFFFFF000, -1)
    test_sub( 42, -10)
    test_sub(-10,  42)
}
